apiVersion: v2
name: gitea-wrapper
description: TaxRakoto IDP wrapper for the official Gitea Helm chart
type: application
version: 0.1.0
appVersion: "1.27.0"
icon: https://docs.gitea.com/img/gitea.svg
dependencies:
  - name: gitea
    version: 12.7.0
    repository: https://dl.gitea.com/charts/
