{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php-app.fullname" . }}-env
  labels:
    {{- include "php-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
