apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-actions-runner
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitea-actions-runner
    app.kubernetes.io/part-of: taxrakoto-idp
automountServiceAccountToken: false
