{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $annotations, $value := .Values.ingress.annotations }}
    {{ $annotations }}: {{ $value | quote }}
    {{- end }}
    {{- /*                                                       */}}
    {{- /************ special annotations if tls is enabled ******/}}
    {{- if .Values.ingress.tls.enabled }}
    {{ .Values.ingress.tls.issuerType }}: {{ .Values.ingress.tls.issuerName }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.servicePort }}
      {{- if .Values.ingress.httpChallengeCatcher.enabled }}
      - path: /.well-known/acme-challenge/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: http-challenge-catcher
            port:
              number: 8080
      {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls.{{ .Release.Name }}
  {{- end }}
  {{- end}}
