apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
{{- if .Values.ingress.httpChallengeCatcher.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: http-challenge-catcher
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: challenge-catcher
{{- end }}